sudo: false
services:
  - elasticsearch
  - couchdb
language: node_js
node_js:
- '0.12'
env:
- ES_HOST=http://localhost:9200
- COUCH_HOST=http://127.0.0.1:5984
before_script:
  - npm install
  - sleep 5
  - test/fixtures/prepare-tests.sh
  - sleep 5
script:
- npm test
cache:
  directories:
  - node_modules
